#%RAML 1.0 NamedExample
value:
  menuItemId: 101
  itemName: Chicken Biriyani
  description: Yummy Hyderabadi Biriyani
  price: 500
  menuId: 1
  links: 
  - linkName: "menu"
    href: "http://localhost:8081/restaurants/1/menus/1"
  - linkName: "menuItemInventory"
    href: "http://localhost:8081/restaurants/1/menus/1/menuItems/101/inventory"