#%RAML 1.0 Trait
 queryParameters:     
      page:
        type: integer
        required: false
        default: 0
        description: Page number to be retrieved
      pageSize:
        type: integer
        required: false
        default: 0
        description: Page Size
  